<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2022 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\EnhancedMaintenanceMode\Console\Command;

class MaintenanceDisableWebsiteCommand extends MaintenanceEnableWebsiteCommand
{
    /**
     * Initialization of the command
     *
     * @return void
     */
    protected function configure(): void
    {
        parent::configure();
        $this->setName('maintenance:disable:website')
            ->setDescription('Disables maintenance mode for a specific website');
    }

    /**
     * Enable maintenance mode
     *
     * @return bool
     */
    protected function isEnable(): bool
    {
        return false;
    }

    /**
     * Get enabled maintenance mode display string
     *
     * @return string
     */
    protected function getDisplayString(): string
    {
        return "<info>Disabled maintenance mode for website '{$this->scopeProvider->getCode()}'</info>";
    }
}
