<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2022 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\EnhancedMaintenanceMode\Console\Command;

class ScopeProvider
{
    const SCOPE_WEBSITE = 'website';
    const SCOPE_STORE = 'store';

    /**
     * @var string|null
     */
    private $scope = self::SCOPE_WEBSITE;

    /**
     * @var string|null
     */
    private $code  = null;

    /**
     * @param string $website
     * @return $this
     */
    public function setScopeWebsite(string $website): self
    {
        $this->scope = self::SCOPE_WEBSITE;
        $this->code = $website;
        return $this;
    }

    /**
     * @param string $store
     * @return $this
     */
    public function setScopeStore(string $store): self
    {
        $this->scope = self::SCOPE_STORE;
        $this->code = $store;
        return $this;
    }

    /**
     * @return bool
     */
    public function isScopeWebsite(): bool
    {
        return $this->scope === self::SCOPE_WEBSITE;
    }

    /**
     * @return bool
     */
    public function isScopeStore(): bool
    {
        return $this->scope === self::SCOPE_STORE;
    }

    /**
     * @return string
     */
    public function getScope(): string
    {
        return (string) $this->scope;
    }

    /**
     * @return string
     */
    public function getCode(): string
    {
        return (string) $this->code;
    }
}
