<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2022 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\EnhancedMaintenanceMode\Plugin\Magento\Framework\App;

use MagedIn\EnhancedMaintenanceMode\Model\MaintenanceMode;
use Magento\Framework\App\MaintenanceMode as Subject;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Exception\NoSuchEntityException;

class MaintenanceModePlugin
{
    /**
     * @var MaintenanceMode
     */
    private $maintenanceMode;

    /**
     * @param MaintenanceMode $maintenanceMode
     */
    public function __construct(
        MaintenanceMode $maintenanceMode
    ) {
        $this->maintenanceMode = $maintenanceMode;
    }

    /**
     * @param Subject $subject
     * @param callable $proceed
     * @param string $remoteAddr
     * @return bool
     * @throws LocalizedException
     * @throws NoSuchEntityException
     */
    public function aroundIsOn(Subject $subject, callable $proceed, string $remoteAddr = ''): bool
    {
        if (!$this->isModuleEnabled()) {
            return $proceed($remoteAddr);
        }
        if(!$this->maintenanceMode->assertScopedMaintenanceMode($subject, $remoteAddr)) {
            return $proceed($remoteAddr);
        }
        return true;
    }

    /**
     * @return bool
     */
    private function isModuleEnabled(): bool
    {
        return true;
    }
}
